cloudflare_api_token: ENC[AES256_GCM,data:c6vkDEqa8Byk1ZxEi2TTzAn1E082j3Ac7zMQGcJI5vMFCQ9Czjc3qkCO/PaZ9mxgo8iapfY=,iv:FvNDJ71CN8Nl0HacXwBcUcSN9UIlxVjEWPQ2g9fzXQo=,tag:VBCESaN3eCQ/zqkUNutI5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFR5YkltdyB3R1hK
            SU1LOXVMVC9RSWl2alg2bTRnZVZCbWpXU2xzZEpHWnNVYWNrRDM0CnplZldtekxx
            VFd4QkFFMkJ2NnZacVRtQXNlV2t2SWgxY2ttOGY2bVlCV0EKLS0tIDBZSUVzVVNt
            QXl0aHhIYUFBa0JhVEVEa1Mxc3o5a1dGeTNTeWRWYXRzVWsKSEb/N4CPVbyH7ufm
            VaoBNGy2Q64ATN1mYWuI5rPennUhzkCpEyihZ3CY+Q82OXP9tC9B1jIhLTKg5jZV
            5H6G3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ7uD0e1fPbqpER1d7CM3EWEnMHlkLNzCfI4NK/Qs+/K
    lastmodified: "2026-10-06T20:48:43Z"
    mac: ENC[AES256_GCM,data:yBU9vm2O9I9VM8bT3q02HSBpX1brJ3LiiHpSqrWaAr997c4wPhbJ70hu/JEzqvPezT2xo/KHBmaUaxZKPsUMcTcvVggLK00P10VnEEmnESX1YtP+6MZSXE5LXQ2SEVwg7f4sUJYNxaDdGHx4SN6Xu1S/WDrxs+hrr1RWOLt3rpQ=,iv:MJAItCmFIw76HPS1WX8RFAJOjXcrRJiJ6wFzX1/WtDE=,tag:x/E55i+XfTtpblku14Q5yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
