name = "acearchive-media-proxy"
main = "build/index.js"
compatibility_date = "2026-10-08"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[cache]
enabled = true

[vars]
DATA_CONNECTOR_URL = "https://connector.acearchive.lgbt"
CACHE_TTL = "14400"
