[package]
name = "acearchive-data-connector"
version = "0.1.0"
edition = "2024"
rust-version = "1.90.0"

[[bin]]
name = "acearchive-data-connector"
path = "src/bin/connector.rs"

[dependencies]
anyhow = "1.0.104"
dotenvy = "0.15.7"
flexi_logger = { version = "0.31.10", features = ["async"] }
log = "0.4.34"
lru = "0.18.5"
reqwest = { version = "0.13.5", features = ["json"] }
secrecy = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
